### ISSUE TITLE
Timelines for the disclosure

### ISSUE THREAD

**Issue by toriningen** [ChenDelong1999/subobjects#1]
Hello!

I am very interested in your work. Are there any timelines on when do you plan to disclose the code? Will you also disclose the checkpoints, and if yes, will it happen together with the code, or at the separate deadline?

Thank you!

**Comment by ChenDelong1999** [comment]
Hi, thank you for your interest in this work! Now we are still working on running more experiments to make it more complete and comprehensive. 

Full codes and weights will be released in the near future as promised. We do not have a concrete timeline for this, but we suggest you check our updates (for both repo and arxiv) around the end of April!

**Comment by AlexandreBrown** [comment]
@ChenDelong1999 Hi, thanks for your great work. Would it also be possible to publish the weights for SeqAE ? I think that this could be used broadly by the research community!  
Cheers!
